OpenGenomeBrowser/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth.views import LoginView, PasswordChangeView
from django.views.generic import RedirectView
from rest_framework import routers

from website.admin.admin import ogb_admin_site

from website.views.rest_api import *

router = routers.DefaultRouter()
router.register(r'genomes', GenomeViewSet)
router.register(r'organisms', OrganismViewSet)
router.register(r'taxids', TaxIDViewSet)
router.register(r'tags', TagViewSet)


class OgbLoginView(LoginView):
    template_name = 'registration/login.html'

    def get_context_data(self, **kwargs):
        from OpenGenomeBrowser import settings
        context = super().get_context_data(**kwargs)
        context['no_help'] = True
        if hasattr(settings, 'LOGIN_MESSAGE'):
            context['login_message'] = settings.LOGIN_MESSAGE
        return context


class OgbPasswordChangeView(PasswordChangeView):
    success_url = '/?info=Password change successful.'


urlpatterns = [
    # favicon.ico
    path('favicon.ico', RedirectView.as_view(url='/static/global/customicons/ogb-circle.svg')),

    path('admin/', ogb_admin_site.urls),

    path('accounts/login/', OgbLoginView.as_view(), name='login'),
    path('accounts/password_change/', OgbPasswordChangeView.as_view(), name="password_change"),
    path('accounts/', include('django.contrib.auth.urls')),

    # django-rest-framework
    path('rest-auth/', include('rest_framework.urls', namespace='rest_framework')),
    path('rest/', include(router.urls)),

    path('', include('website.urls')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
    # Serving files uploaded by a user during development
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

website/urls.py
from django.urls import path, re_path

from website.views import *

app_name = 'website'

urlpatterns = [
    # ex: /
    path('', Home.home_view, name='index'),

    # ex: /files_html and /files_json
    re_path(r'files_html/.*$', Files.files_html, name='files-html'),
    re_path(r'files_json/.*$', Files.files_json, name='files-json'),
    re_path(r'files_cache/.*$', Files.files_cache, name='files-cache'),

    # ex: /genomes
    path('genomes/', GenomeFilter.filter_view, name='genomes'),

    # ex: /organism/{identifier}
    path('organism/<str:slug>/', OrganismDetailView.as_view(), name='organism'),

    # ex: /genome/{name}
    path('genome/<str:slug>/', GenomeDetailView.as_view(), name='genome'),

    # ex: /taxid/{taxid} and /taxname/{taxscientificname}
    path('taxid/<str:slug>/', TaxIDDetailView.as_view(), name='taxid'),
    path('taxname/<str:slug>/', TaxIDDetailView.redirect_taxname, name='taxname'),

    # ex: /tag/{tag}
    path('tag/<str:slug>/', TagDetailView.as_view(), name='tag'),

    # ex: /gene/{name}
    path('gene/<str:slug>/', GeneDetailView.as_view(), name='gene'),

    # ex: /annotation/{name}
    path('annotations/', AnnotationFilter.filter_view, name='annotation-filter'),
    path('annotation/<str:slug>/', AnnotationDetailView.as_view(), name='annotation'),

    # ex: /annotation-search/?annotations={K01626}+{EC:4.4.4.4}&genomes={organism1}+{organism2}
    path('annotation-search/', AnnotationSearch.annotation_view, name='annotation-search'),
    path('annotation-search-matrix/', AnnotationSearch.matrix, name='annotation-search-matrix'),

    # ex: /pathway/?map_slug={kegg-map-00400}&genomes={organism1}+{organism2}
    path('pathway/', PathwayView.pathway_view, name='pathway'),

    # ex: /trees/?genomes={organism1}+{organism2}
    path('trees/', Trees.trees, name='trees'),

    # ex: /trees/?genomes={organism1}+{organism2}
    path('dotplot/', Dotplot.dotplot_view, name='dotplot'),

    # ex: /compare-genes/?genes={gene 1}+{gene 2}
    path('compare-genes/', CompareGenes.compare, name='compare-genes'),

    # ex: /gene-trait-matching/?g1={organism1}+{organism2}&g2={organism3}+{organism4}
    path('gene-trait-matching/', GeneTraitMatching.gtm_view, name='gene-trait-matching'),
    path('gene-trait-matching-table/', GeneTraitMatching.gtm_table, name='gene-trait-matching-table'),

    # ex: /gene-trait-matching/?g1={organism1}+{organism2}&g2={organism3}+{organism4}
    path('flower-plot/', FlowerPlot.flower_view, name='flower-plot'),
    path('flower-plot-svg/', FlowerPlot.flower_svg, name='flower-plot-svg'),

    # ex: /blast/?query={fasta}&genomes={organism1}+{organism2}
    path('blast/', Blast.blast_view, name='blast'),
    path('blast/submit', Blast.blast_submit, name='blast-submit'),

    # ex: /downloader
    path('downloader/', Downloader.downloader_view, name='downloader'),
    path('downloader/submit/', Downloader.downloader_submit, name='downloader-submit'),
    path('downloader/is_loaded/', Downloader.downloader_is_loaded, name='downloader-is-loaded'),

    # ex: /api/{...}
    path('api/autocomplete-annotations/', Api.autocomplete_annotations, name='api-autocomplete-annotations'),
    path('api/autocomplete-pathway/', Api.autocomplete_pathway, name='api-autocomplete-pathway'),
    path('api/autocomplete-genomes/', Api.autocomplete_genomes, name='api-autocomplete-genomes'),
    path('api/autocomplete-genes/', Api.autocomplete_genes, name='api-autocomplete-genes'),
    path('api/validate-pathwaymap/', Api.validate_pathwaymap, name='api-validate-pathwaymap'),
    path('api/validate-genomes/', Api.validate_genomes, name='api-validate-genomes'),
    path('api/validate-genes/', Api.validate_genes, name='api-validate-genes'),
    path('api/validate-annotations/', Api.validate_annotations, name='api-validate-annotations'),
    path('api/genome-identifier-to-species/', Api.genome_identifier_to_species, name='api-genome-identifier-to-species'),
    path('api/annotation-to-type/', Api.annotation_to_type, name='api-annotation-to-type'),
    path('api/dna-feature-viewer-single/', Api.dna_feature_viewer_single, name='api-dna-feature-viewer'),
    path('api/dna-feature-viewer-multi/', Api.dna_feature_viewer_multi, name='api-dna-feature-viewer'),
    path('api/align/', Api.align, name='api-align'),
    path('api/get-gene/', Api.get_gene, name='api-get-gene'),
    path('api/get-annotation/', Api.get_annotation, name='api-get-annotation'),
    path('api/get-tree/', Api.get_tree, name='api-get-tree'),
    path('api/reload-orthofinder/', Api.reload_orthofinder, name='api-reload-orthofinder'),
    path('api/get-dotplot/', get_dotplot, name='api-get-dotplot'),
    path('api/get-dotplot-annotations/', get_dotplot_annotations, name='api-get-dotplot-annotations'),
    path('api/score-pathway-maps/', PathwayView.score_pathway_maps, name='api-score-pathway-maps'),

    # ex /test-click-menu/
    path('test-click-menu/', ClickMenu.click_view, name='test-click-menu'),
]

website/models/Genome.py
from django.db.models.manager import Manager
from hashlib import sha224
from django.db import models
from django.db.models import JSONField
from django.contrib.postgres.fields import ArrayField
from .Organism import Organism
from .TaxID import TaxID
from .Tag import Tag
from .GenomeContent import GenomeContent
from OpenGenomeBrowser import settings
from functools import cached_property
from website.models.helpers.backup_file import read_file_or_default, overwrite_with_backup
from website.models.helpers import AnnotatedGenomeManager


class Genome(models.Model):
    """
    Represents a measurement of a organism.

    Imported from database/genomes/organism/genomes/*
    """

    """
    todo: ensure tags are imported, and saved to metadata if changed through admin
    """
    objects = Manager()
    annotated_objects = AnnotatedGenomeManager()

    # MANDATORY general information about the isolate
    identifier = models.CharField('Unique identifier', max_length=50, unique=True)
    organism = models.ForeignKey(Organism, on_delete=models.CASCADE, null=True, blank=True)
    genomecontent = models.OneToOneField(GenomeContent, on_delete=models.CASCADE, null=True, blank=True)

    tags = models.ManyToManyField(Tag, blank=True)
    contaminated = models.BooleanField('Contaminated?', default=False)
    old_identifier = models.CharField('Old identifier', max_length=50, null=True, blank=True)

    # information about isolation
    isolation_date = models.DateField('Isolation date', null=True, blank=True)
    env_broad_scale = ArrayField(models.TextField(), verbose_name='Broad isolation environment', default=list, blank=True)
    env_local_scale = ArrayField(models.TextField(), verbose_name='Local isolation environment', default=list, blank=True)
    env_medium = ArrayField(models.TextField(), verbose_name='Environment medium', default=list, blank=True)
    growth_condition = models.CharField('Growth condition', max_length=100, null=True, blank=True)
    geographical_coordinates = models.CharField('Geographical coordinates', max_length=200, null=True, blank=True)
    geographical_name = models.CharField('Geographical name', max_length=50, null=True, blank=True)

    # information about sequencing
    library_preparation = models.CharField('Library Preparation', max_length=40, null=True, blank=True)
    sequencing_tech = models.CharField('Sequencing technology', max_length=40, null=True, blank=True)
    sequencing_tech_version = models.CharField('Sequencing technology version', max_length=20, null=True, blank=True)
    sequencing_date = models.DateField('Sequencing date', null=True, blank=True)
    read_length = models.CharField('Read length', max_length=8, null=True, blank=True)
    sequencing_coverage = models.CharField('Sequencing coverage', max_length=8, null=True, blank=True)

    # information about assembly
    assembly_tool = models.CharField('Assembly tool', max_length=40, null=True, blank=True)
    assembly_version = models.CharField('Assembly version', max_length=40, null=True, blank=True)
    assembly_date = models.DateField('Assembly date', null=True, blank=True)

    assembly_fasta_file = models.CharField(max_length=200)
    assembly_gc = models.FloatField('GC content', null=True, blank=True)
    assembly_longest_scf = models.IntegerField('Longest scaffold', null=True, blank=True)
    assembly_size = models.IntegerField('Assembly size', null=True, blank=True)
    assembly_nr_scaffolds = models.IntegerField('Number of scaffolds', null=True, blank=True)
    assembly_n50 = models.IntegerField('N50', null=True, blank=True)
    assembly_gaps = models.IntegerField('Number of gaps', null=True, blank=True)
    assembly_ncount = models.IntegerField('Total Ns', null=True, blank=True)
    nr_replicons = models.IntegerField('Number of replicons', null=True, blank=True)

    # contamination analysis
    custom_tables = JSONField(default=list, blank=True, null=True)

    # information about CDS prediction
    cds_tool = models.CharField('Primary annotation tool', max_length=50, null=True, blank=True)
    cds_tool_date = models.DateField('Date of primary annotation', null=True, blank=True)
    cds_tool_version = models.CharField('Version of primary annotation', max_length=20, null=True, blank=True)
    cds_tool_faa_file = models.CharField(max_length=200)  # MANDATORY
    cds_tool_gbk_file = models.CharField(max_length=200)  # MANDATORY
    cds_tool_gff_file = models.CharField(max_length=200)  # MANDATORY
    cds_tool_ffn_file = models.CharField(max_length=200, null=True, blank=True)
    cds_tool_sqn_file = models.CharField(max_length=200, null=True, blank=True)

    BUSCO = JSONField(default=dict)  # {C:2,D:2,F:2,M:2,S:2,T:2]}  +  {dataset: firmicutes_odb9}  +  {dataset_creation_date: "2000-01-31"}
    BUSCO_percent_single = models.DecimalField(max_digits=4, decimal_places=1, null=True, blank=True)

    COG = JSONField(default=dict)  # {'J': 152.5, 'A': 2, 'K': 29.333, ... }

    # information about annotation
    custom_annotations = JSONField(default=list, blank=True, null=True)  # [{"date": "2016-02-29", "file": "FAM19038.ko", "type": "KG"}]

    # accession numbers if the genome has been published
    bioproject_accession = models.CharField('Bioproject accession', max_length=20, null=True, blank=True)
    biosample_accession = models.CharField('Biosample accession', max_length=20, null=True, blank=True)
    genome_accession = models.CharField('Genome accession', max_length=20, null=True, blank=True)

    # literature references
    literature_references = JSONField('Literature references', default=list, blank=True, null=True)

    def __str__(self):
        return self.identifier

    def natural_key(self):
        return self.identifier

    @property
    def parent(self):
        return self.taxid

    def set_representative(self):
        self.organism.set_representative(self)

    @property
    def taxid(self) -> TaxID:
        return self.organism.taxid

    @property
    def taxscientificname(self):
        return self.taxid.taxscientificname

    @property
    def html(self):
        classes = ['genome', 'ogb-tag']
        if not self.is_representative:
            classes.append('no-representative')
        if self.contaminated:
            classes.append('contaminated')
        if self.restricted:
            classes.append('restricted')
        return f'<span class="{" ".join(classes)}" data-species="{self.taxid.taxscientificname}">{self.identifier}</span>'

    @property
    def html_warning_stripes(self):
        classes = []
        print(self, self.is_representative)
        if not self.is_representative:
            classes.append('no-representative')
        if self.contaminated:
            classes.append('contaminated')
        if self.restricted:
            classes.append('restricted')

        return ' '.join(classes)

    @property
    def is_representative(self) -> bool:
        return hasattr(self, 'representative') and self.representative is not None

    @property
    def restricted(self) -> bool:
        return self.organism.restricted

    @property
    def genomecontent__n_genes(self) -> int:
        return self.genomecontent.n_genes

    def base_path(self, relative=True) -> str:
        rel = F"organisms/{self.organism.name}/genomes/{self.identifier}"
        return rel if relative else f'{settings.FOLDER_STRUCTURE}/{rel}'

    def assembly_fasta(self, relative=True) -> str:  # mandatory
        return F"{self.base_path(relative)}/{self.assembly_fasta_file}"

    def cds_faa(self, relative=True) -> str:  # mandatory
        return F"{self.base_path(relative)}/{self.cds_tool_faa_file}"

    def cds_gbk(self, relative=True) -> str:  # mandatory
        return F"{self.base_path(relative)}/{self.cds_tool_gbk_file}"

    def cds_gff(self, relative=True) -> str:  # mandatory
        return F"{self.base_path(relative)}/{self.cds_tool_gff_file}"

    def cds_ffn(self, relative=True) -> str:
        if not self.cds_tool_ffn_file:
            return None
        return F"{self.base_path(relative)}/{self.cds_tool_ffn_file}"

    def cds_sqn(self, relative=True) -> str:
        if not self.cds_tool_sqn_file:
            return None
        return F"{self.base_path(relative)}/{self.cds_tool_sqn_file}"

    @cached_property
    def all_tags(self):
        return (self.tags.all() | self.organism.tags.all()).distinct()

    @property
    def metadata_json(self) -> str:
        return f'{settings.FOLDER_STRUCTURE}/organisms/{self.organism.name}/genomes/{self.identifier}/genome.json'

    def markdown_path(self, relative=True) -> str:
        return F"{self.base_path(relative)}/genome.md"

    def markdown(self, default=None) -> str:
        return read_file_or_default(file=self.markdown_path(relative=False), default=default, default_if_empty=True)

    def set_markdown(self, md: str, user: str = None):
        overwrite_with_backup(file=self.markdown_path(relative=False), content=md, user=user, delete_if_empty=True)

    @staticmethod
    def hash_genomes(genomes) -> str:
        identifiers = sorted(set(g.identifier for g in genomes))
        identifier_string = ' '.join(identifiers)
        hash = sha224(identifier_string.encode('utf-8')).hexdigest()
        assert len(hash) == 56
        return hash

    def invariant(self):
        from website.serializers import GenomeSerializer
        from db_setup.check_metadata import genome_metadata_is_valid
        from db_setup.FolderLooper import MockGenome, MockOrganism

        assert self.identifier.startswith(self.organism.name)

        # ensure metadata is valid
        g_s_g = GenomeSerializer(self)
        genome_state = g_s_g.data
        assert genome_metadata_is_valid(genome_state, path_to_genome=self.base_path(relative=False), raise_exception=True)

        # ensure metadata json matches genome
        m_o = MockOrganism(path=self.organism.base_path(relative=False))
        m_g = MockGenome(path=self.base_path(relative=False), organism=m_o)

website/views/ClickMenu.py
from django.shortcuts import render
from website.models import TaxID, Annotation, Genome, Organism, Gene


def click_view(request):
    context = dict(
        title='Test Click Menu',
        taxids=TaxID.objects.all()[:5],
        annotations=Annotation.objects.all().distinct('anno_type'),
        genomes=Genome.objects.order_by('-contaminated', '-representative', 'organism__restricted').all()[:5],
        organisms=Organism.objects.order_by('-restricted').all()[:5],
        genes=Gene.objects.all()[:5]
    )

    return render(request, 'global/test_click_menu.html', context)

website/templates/website/annotation_search_matrix.html
<div class="container">
    <h3>Coverage Matrix</h3>
</div>

<div class="container-fluid prevent-overflow">

    {{ matrix|safe }}

</div>

website/templates/website/gene_detail.html
{% extends 'global/base.html' %}
{% load static %}

{% block styles %}
    <!-- Site-specific css/js -->
    <link rel="stylesheet" type="text/css" href="{% static 'global/css/detail.css' %}"/>
    <link rel="stylesheet" type="text/css" href="{% static 'global/css/sequence-viewer.css' %}" id="sequence-stylesheet"/>
    <link rel="stylesheet" type="text/css" href="{% static 'global/css/annotype_color.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'global/css/taxid_color.css' %}">

    <script src="{% static 'dna-feature-viewer/js/dna-feature-viewer.js' %}"></script>
    <script src="{% static 'global/js/bokeh.min.js' %}"></script>
    <script src="{% static 'global/js/bokeh-tables.min.js' %}"></script>
    <script src="{% static 'global/js/bokeh-widgets.min.js' %}"></script>

{% endblock %}

{% block sidebar %}

    <div class="sidebar-subcontent form-check form-check-inline">
        <label class="form-check-label" for="colorize-sequence-checkbox"><a>Colorize sequences?</a></label>
        <input class="form-check-input" type="checkbox" id="colorize-sequence-checkbox"
               onclick="toggleColorizeSequence()">
    </div>

    <div class="sidebar-subcontent form-check form-check-inline">
        <label class="form-check-label" for="formControlRange"><a>Set range around gene locus</a></label>
        <input type="range" class="form-control-range" id="formControlRange" min="3000" max="300000" value="10000">

        <span>update range to <b id="range-span">10000</b> bp</span>
        <button type="button" class="btn btn-primary" onclick="load_dfvm()">Reload Gene Locus</button>
    </div>

{% endblock %}

{% block breadcrum %}
    <!-- Breadcrumb -->
    <div class="breadcrumb-push"></div>
    <nav aria-label="breadcrumb" class="breadcrumb-fixed">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"></li>
            <!-- Taxid -->
            <li class="breadcrumb-item">
                <a href="{% url 'website:taxid' slug=gene.genomecontent.genome.taxid.id %}"> TAXID {{ gene.genomecontent.genome.taxid.id }}</a>
            </li>
            <!-- Organism -->
            <li class="breadcrumb-item">
                <a href="{% url 'website:organism' slug=gene.genomecontent.organism %}"> ORGANISM {{ gene.genomecontent.organism }}</a>
            </li>
            <!-- Genome -->
            <li class="breadcrumb-item">
                <a href="{% url 'website:genome' slug=gene.genomecontent %}"> GENOME {{ gene.genomecontent }}</a>
            </li>
            <!-- Gene -->
            <li class="breadcrumb-item active" aria-current="page">
                <span>GENE {{ gene }}</span>
            </li>
        </ol>
    </nav>
{% endblock %}

{% block body %}

    <section>
        <!-- title -->
        <div class="container black-links">
            <!-- locus tag -->
            <span class="type-label">locus tag:</span>
            <span class="h1" onclick="showGeneClickMenu(event, '{{ gene }}', [])">
                {{ gene }}</span>

            <!-- genome -->
            <span class="type-label">genome:</span>
            <span class="h2" onclick="showGenomeClickMenu(event, 'auto', '{{ gene.genomecontent.taxid }}')">{{ gene.genomecontent }}</span>

            <!-- taxid -->
            {% if gene.genomecontent.taxid %}<br>
                <span class="type-label">species:</span>
                <span class="h3" onclick="showTaxidClickMenu(event, '{{ gene.genomecontent.taxid }}')">
                    {{ gene.genomecontent.taxid }}</span>
                <span class="type-label">taxid:</span>
                <span class="h3" style="{{ gene.genomecontent.taxid.html_style }}"
                      onclick="showTaxidClickMenu(event, '{{ gene.genomecontent.taxid }}')">{{ gene.genomecontent.taxid.id }}</span>
            {% endif %}

        </div>

    </section>
    <section>

        <!-- Annotations -->
        <div class="container">
            <hr class="featurette-divider">

            <h3>Annotations</h3>
            <!-- Annotations: Table -->
            <div style="max-height: 30rem;overflow-y: auto">
                <table id="annotations-list" class="table no-bottom-padding">
                    <thead class="thead-dark">
                    <tr>
                        <th scope="col">Type</th>
                        <th scope="col">Name</th>
                        <th scope="col">Description</th>
                        <th scope="col">Pathways</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for anno in annotations %}
                        <tr>
                            <th scope="row">
                                <div class="annotation"
                                     data-annotype="{{ anno.anno_type }}">{{ anno.anno_type_verbose }}</div>
                            </th>
                            <td>{{ anno.html|safe }}</td>
                            <td>{{ anno.description }}</td>
                            <td>{% for pathway in anno.pathwaymap_set.all %}{{ pathway.html|safe }}{% endfor %}</td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>

    </section>
    <section>

        {% if pathways %}
            <!-- Pathways -->
            <div class="container">

                <hr class="featurette-divider">

                <h3>Occurs in the following pathway maps:</h3>
                <!-- Annotations: Table -->
                <div style="max-height: 30rem;overflow-y: auto">
                    <table id="annotations-list" class="table no-bottom-padding table-sm">
                        <thead class="thead-dark">
                        <tr>
                            <th scope="col">Pathway</th>
                            <th scope="col">Description</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for pathway in pathways %}
                            <tr>
                                <th scope="row">
                                    {{ pathway.html|safe }}
                                </th>
                                <td>{{ pathway.title }}</td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>

            </div>

        {% endif %}

    </section>
    <section>

        <!-- Sequences -->
        <div class="container">
            <hr class="featurette-divider">

            <h3>Sequences</h3>

            <p>Nucleotide sequence (GC-content: {{ gene.gc_content|floatformat:1 }} %):</p>
            <div class="sequence-div sequence-nucleotide">{{ fasta_nucleotide|safe }}</div>
            <br>
            <p>Protein sequence:</p>
            <div class="sequence-div sequence-protein">{{ fasta_protein|safe }}</div>
        </div>

    </section>
    <section>

        <!-- GenBank info -->
        <div class="container">
            <hr class="featurette-divider">
            <h3>GenBank Info</h3>

            {% for key, value in gene.get_gbk_qualifiers.items %}
                {{ key }} - {{ value|join:" --AND-- " }}<br>
            {% endfor %}
        </div>

    </section>
    <section>

        <!-- Gene Locus -->
        <div class="container">
            <hr class="featurette-divider">

            <h3>Gene Locus</h3>

            {% if scaffold_id %}<p>Located on scaffold {{ scaffold_id }}</p>{% endif %}

            <div id="gene-locus"></div>

            <hr class="featurette-divider">
        </div>

    </section>


    {% if sls_ids %}

        <section>
            <script type="module" src="{% static 'global/js/swissbiopics.js' %}"></script>

            <template id="sibSwissBioPicsStyle">
                <style>
                    #swissbiopic {
                        display: flex !important;
                        flex-direction: column-reverse !important;
                    }

                    .subcell_description, svg .subcell_name {
                        display: none;
                    }

                    ul > li > a {
                        font-style: oblique;
                    }
                </style>
            </template>

            <template id="sibSwissBioPicsSlLiItem">
                <li class="subcellular_location">
                    <a class="subcell_name"></a>
                    <span class="subcell_description"></span>
                </li>
            </template>

            <div class="container">
                <h3 class="d-flex h-100" data-toggle="collapse" href="#locusterms" aria-controls="locusterms" aria-expanded="true">
                    Cellular location
                    <img src="{% static 'global/ionicons/ios-arrow-down.svg' %}" class="expand-white-img align-self-center ml-auto" alt="expand">
                </h3>

                <div class="collapse" id="locusterms">
                    Responsible annotations: <br>
                    {% for sl_id, annotation in location_annotations %}
                        <a href="https://www.nextprot.org/term/{{ sl_id }}/">{{ sl_id }}</a>: {{ annotation.html|safe }}
                        <span>{{ annotation.description }}</span>
                        <br>
                    {% endfor %}
                </div>

                <sib-swissbiopics-sl taxid="{{ taxid }}" sls="{{ sls_ids|join:',' }}"></sib-swissbiopics-sl>

                <hr class="featurette-divider">
            </div>

        </section>

    {% endif %}

    <section>

        <!-- Go to prev / next Gene -->
        <div class="container" style="display: flex; justify-content: space-between">
            <div>
                {% if prev_gene %}
                    <a href="{% url 'website:gene' slug=prev_gene %}">
                        <img src="{% static 'global/ionicons/ios-arrow-dropleft.svg' %}"
                             style="height: 3rem"> {{ prev_gene }}
                    </a>
                {% endif %}
            </div>
            <div>
                {% if next_gene %}
                    <a href="{% url 'website:gene' slug=next_gene %}">
                        {{ next_gene }} <img src="{% static 'global/ionicons/ios-arrow-dropright.svg' %}"
                                             style="height: 3rem">
                    </a>
                {% endif %}
            </div>
        </div>
        <div id="context-menu"></div>

    </section>


{% endblock %}

{% block end %}
    <script>
        let draw;

        const gene = "{{ gene }}"

        $(document).ready(function () {
            load_dfvm()

            $(".ogb-tag.annotation")
                .ogbTooltip()
                .on("click", function () {
                    showAnnotationClickMenu(event)
                })

            $(".ogb-tag.pathway")
                .ogbTooltip()
                .on("click", function () {
                    showPathwayClickMenu(event, ['{{ gene.genomecontent }}'])
                })

        })

        let load_dfvm = function () {
            $('#gene-locus').empty()
            load_dna_feature_viewer_single(
                gene_identifier = gene,
                target_div = $('#gene-locus'),
                span = parseInt($('#range-span').text())
            )
        }

        $('#formControlRange').on('change', function (e) {
            const span = $('#formControlRange').val()
            $('#range-span').text(span)
        })


    </script>
{% endblock %}