OpenGenomeBrowser/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth.views import LoginView, PasswordChangeView
from django.views.generic import RedirectView
from rest_framework import routers

from website.admin.admin import ogb_admin_site

from website.views.rest_api import *

router = routers.DefaultRouter()
router.register(r'genomes', GenomeViewSet)
router.register(r'organisms', OrganismViewSet)
router.register(r'taxids', TaxIDViewSet)
router.register(r'tags', TagViewSet)


class OgbLoginView(LoginView):
    template_name = 'registration/login.html'

    def get_context_data(self, **kwargs):
        from OpenGenomeBrowser import settings
        context = super().get_context_data(**kwargs)
        context['no_help'] = True
        if hasattr(settings, 'LOGIN_MESSAGE'):
            context['login_message'] = settings.LOGIN_MESSAGE
        return context


class OgbPasswordChangeView(PasswordChangeView):
    success_url = '/?info=Password change successful.'


urlpatterns = [
    # favicon.ico
    path('favicon.ico', RedirectView.as_view(url='/static/global/customicons/ogb-circle.svg')),

    path('admin/', ogb_admin_site.urls),

    path('accounts/login/', OgbLoginView.as_view(), name='login'),
    path('accounts/password_change/', OgbPasswordChangeView.as_view(), name="password_change"),
    path('accounts/', include('django.contrib.auth.urls')),

    # django-rest-framework
    path('rest-auth/', include('rest_framework.urls', namespace='rest_framework')),
    path('rest/', include(router.urls)),

    path('', include('website.urls')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
    # Serving files uploaded by a user during development
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

website/urls.py
from django.urls import path, re_path

from website.views import *

app_name = 'website'

urlpatterns = [
    # ex: /
    path('', Home.home_view, name='index'),

    # ex: /files_html and /files_json
    re_path(r'files_html/.*$', Files.files_html, name='files-html'),
    re_path(r'files_json/.*$', Files.files_json, name='files-json'),
    re_path(r'files_cache/.*$', Files.files_cache, name='files-cache'),

    # ex: /genomes
    path('genomes/', GenomeFilter.filter_view, name='genomes'),

    # ex: /organism/{identifier}
    path('organism/<str:slug>/', OrganismDetailView.as_view(), name='organism'),

    # ex: /genome/{name}
    path('genome/<str:slug>/', GenomeDetailView.as_view(), name='genome'),

    # ex: /taxid/{taxid} and /taxname/{taxscientificname}
    path('taxid/<str:slug>/', TaxIDDetailView.as_view(), name='taxid'),
    path('taxname/<str:slug>/', TaxIDDetailView.redirect_taxname, name='taxname'),

    # ex: /tag/{tag}
    path('tag/<str:slug>/', TagDetailView.as_view(), name='tag'),

    # ex: /gene/{name}
    path('gene/<str:slug>/', GeneDetailView.as_view(), name='gene'),

    # ex: /annotation/{name}
    path('annotations/', AnnotationFilter.filter_view, name='annotation-filter'),
    path('annotation/<str:slug>/', AnnotationDetailView.as_view(), name='annotation'),

    # ex: /annotation-search/?annotations={K01626}+{EC:4.4.4.4}&genomes={organism1}+{organism2}
    path('annotation-search/', AnnotationSearch.annotation_view, name='annotation-search'),
    path('annotation-search-matrix/', AnnotationSearch.matrix, name='annotation-search-matrix'),

    # ex: /pathway/?map_slug={kegg-map-00400}&genomes={organism1}+{organism2}
    path('pathway/', PathwayView.pathway_view, name='pathway'),

    # ex: /trees/?genomes={organism1}+{organism2}
    path('trees/', Trees.trees, name='trees'),

    # ex: /trees/?genomes={organism1}+{organism2}
    path('dotplot/', Dotplot.dotplot_view, name='dotplot'),

    # ex: /compare-genes/?genes={gene 1}+{gene 2}
    path('compare-genes/', CompareGenes.compare, name='compare-genes'),

    # ex: /gene-trait-matching/?g1={organism1}+{organism2}&g2={organism3}+{organism4}
    path('gene-trait-matching/', GeneTraitMatching.gtm_view, name='gene-trait-matching'),
    path('gene-trait-matching-table/', GeneTraitMatching.gtm_table, name='gene-trait-matching-table'),

    # ex: /gene-trait-matching/?g1={organism1}+{organism2}&g2={organism3}+{organism4}
    path('flower-plot/', FlowerPlot.flower_view, name='flower-plot'),
    path('flower-plot-svg/', FlowerPlot.flower_svg, name='flower-plot-svg'),

    # ex: /blast/?query={fasta}&genomes={organism1}+{organism2}
    path('blast/', Blast.blast_view, name='blast'),
    path('blast/submit', Blast.blast_submit, name='blast-submit'),

    # ex: /downloader
    path('downloader/', Downloader.downloader_view, name='downloader'),
    path('downloader/submit/', Downloader.downloader_submit, name='downloader-submit'),
    path('downloader/is_loaded/', Downloader.downloader_is_loaded, name='downloader-is-loaded'),

    # ex: /api/{...}
    path('api/autocomplete-annotations/', Api.autocomplete_annotations, name='api-autocomplete-annotations'),
    path('api/autocomplete-pathway/', Api.autocomplete_pathway, name='api-autocomplete-pathway'),
    path('api/autocomplete-genomes/', Api.autocomplete_genomes, name='api-autocomplete-genomes'),
    path('api/autocomplete-genes/', Api.autocomplete_genes, name='api-autocomplete-genes'),
    path('api/validate-pathwaymap/', Api.validate_pathwaymap, name='api-validate-pathwaymap'),
    path('api/validate-genomes/', Api.validate_genomes, name='api-validate-genomes'),
    path('api/validate-genes/', Api.validate_genes, name='api-validate-genes'),
    path('api/validate-annotations/', Api.validate_annotations, name='api-validate-annotations'),
    path('api/genome-identifier-to-species/', Api.genome_identifier_to_species, name='api-genome-identifier-to-species'),
    path('api/annotation-to-type/', Api.annotation_to_type, name='api-annotation-to-type'),
    path('api/dna-feature-viewer-single/', Api.dna_feature_viewer_single, name='api-dna-feature-viewer'),
    path('api/dna-feature-viewer-multi/', Api.dna_feature_viewer_multi, name='api-dna-feature-viewer'),
    path('api/align/', Api.align, name='api-align'),
    path('api/get-gene/', Api.get_gene, name='api-get-gene'),
    path('api/get-annotation/', Api.get_annotation, name='api-get-annotation'),
    path('api/get-tree/', Api.get_tree, name='api-get-tree'),
    path('api/reload-orthofinder/', Api.reload_orthofinder, name='api-reload-orthofinder'),
    path('api/get-dotplot/', get_dotplot, name='api-get-dotplot'),
    path('api/get-dotplot-annotations/', get_dotplot_annotations, name='api-get-dotplot-annotations'),
    path('api/score-pathway-maps/', PathwayView.score_pathway_maps, name='api-score-pathway-maps'),

    # ex /test-click-menu/
    path('test-click-menu/', ClickMenu.click_view, name='test-click-menu'),
]

website/views/AnnotationDetailView.py
from website.models import Annotation
from django.views.generic import DetailView


class AnnotationDetailView(DetailView):
    model = Annotation
    slug_field = 'name'
    template_name = 'website/annotation_detail.html'
    context_object_name = 'annotation'

    def get_context_data(self, **kwargs):
        context = super(AnnotationDetailView, self).get_context_data(**kwargs)
        context['no_help'] = True

        a: Annotation = self.object

        context['title'] = a.name

        genes = a.gene_set.all().order_by('identifier')[:2000].prefetch_related('genomecontent__genome__organism__taxid')

        context['capped'] = len(genes) == 2000

        genomecontent_to_gene = {}
        for gene in genes:
            if gene.genomecontent not in genomecontent_to_gene:
                genomecontent_to_gene[gene.genomecontent] = [gene]
            else:
                genomecontent_to_gene[(gene.genomecontent)].append(gene)

        context['genome_to_gene'] = genomecontent_to_gene

        return context

website/views/AnnotationFilter.py
from django.core.exceptions import FieldError
from django.core.paginator import Paginator
from django.shortcuts import render

from website.models import Annotation, PathwayMap
from website.models.Annotation import annotation_types
from website.views.helpers.extract_errors import extract_errors

from website.views.helpers.magic_string import MagicQueryManager
from website.views.helpers.extract_requests import extract_data, extract_data_or


def simple_filter(qs, lookup_expr, field_id, request, context):
    query = extract_data_or(request=request, key=field_id)
    if query:
        return qs.filter(**{lookup_expr: query}), context
    else:
        return qs, context


def genomes_filter(qs, lookup_expr, field_id, request, context):
    mgm_id = 'magic_query_manager' if field_id == 'genomes' else 'magic_query_manager_not'
    genomes = extract_data_or(request=request, key=field_id, list=True, sep=',')

    if genomes:
        try:
            magic_query_manager = MagicQueryManager(queries=genomes)
            context[mgm_id] = magic_query_manager
            if len(magic_query_manager.all_genomes) == 0:
                context['error_danger'].append('Query did not find any genomes.')
            for g in magic_query_manager.all_genomes:
                if field_id == 'genomes':
                    qs = qs.filter(genomecontent__in=[g.identifier])
                else:
                    qs = qs.exclude(genomecontent__in=[g.identifier])
        except Exception as e:
            context['error_danger'].append(str(e))

    return qs, context


def get_pathways() -> list:
    try:
        return [(m.slug, str(m)) for m in PathwayMap.objects.all()]
    except:
        from logging import warning
        warning('Could not get PathwayMap objects.')
        return []


class AnnotationFilter:
    filter_fields = dict(
        genomes=dict(
            label='Genomes', lookup_expr=None, filter_function=genomes_filter, hidden=True),
        not_genomes=dict(
            label='Not genomes', lookup_expr=None, filter_function=genomes_filter, hidden=True),
        name=dict(
            label='Name (regex)', lookup_expr='name__regex', filter_function=simple_filter),
        description=dict(
            label='Description (regex)', lookup_expr='description__regex', filter_function=simple_filter),
        anno_type=dict(
            label='Anno type', lookup_expr='anno_type', filter_function=simple_filter,
            choices=[('', '-------')] + [(abbr, f'{at.name} ({abbr})') for abbr, at in annotation_types.items()]),
        pathway_map=dict(
            label='Pathway map', lookup_expr='pathwaymap', filter_function=simple_filter,
            choices=[('', '-------')] + get_pathways())
    )

    paginate_by = 30
    pagination_options = ['All', 10, 20, 30, 50, 100, 500, 1000]

    @classmethod
    def filter_queryset(cls, request, context):
        qs = Annotation.objects
        filter_fields = cls.filter_fields.copy()
        for field_id, filter_field in filter_fields.items():
            filter_field['data'] = ''
            data = extract_data_or(request=request, key=field_id)
            if data:
                filter_field['data'] = data
                filter_function = filter_field['filter_function']
                qs, context = filter_function(qs, filter_field['lookup_expr'], field_id, request, context)

        return qs.all(), filter_fields

    @classmethod
    def filter_view(cls, request):
        context = extract_errors(request, dict(title='Annotation filter', no_help=True))

        qs, filter_fields = cls.filter_queryset(request, context)

        # order queryset consistent results with pagination
        order_by = extract_data_or(request, 'order_by', default='name')
        try:
            qs = qs.order_by(order_by)
        except FieldError:
            context['error_danger'].append(f"Could not order_by '{order_by}', ordering by 'name' instead.")
            qs = qs.order_by('name')

        context['filter_fields'] = filter_fields

        paginate_by = extract_data(request, 'paginate_by')
        if paginate_by == 'All':
            context['object_list'] = qs
        else:
            paginate_by = int(paginate_by) if type(paginate_by) is str and paginate_by.isnumeric() else cls.paginate_by
            paginator = Paginator(qs, paginate_by)
            try:
                page = int(extract_data(request, 'page'))
            except:
                page = 1

            page_obj = paginator.page(page)
            context['page_obj'] = page_obj
            context['object_list'] = page_obj.object_list
            context['paginator'] = paginator

        context['paginated_by'] = paginate_by
        context['pagination_options'] = cls.pagination_options
        if paginate_by not in cls.pagination_options:
            context['pagination_options'].append(paginate_by)

        return render(request, 'website/annotation_filter.html', context)

website/views/Blast.py
from django.shortcuts import render, HttpResponse
from django.http import HttpResponseBadRequest, JsonResponse

from website.views.helpers.extract_errors import extract_errors
from website.views.helpers.magic_string import MagicQueryManager, MagicError
from website.views.helpers.extract_requests import contains_data, extract_data
from plugins import calculate_blast
from ncbi_blast import Blast

CHOICE_TO_SETTINGS = dict(
    blastn_ffn=dict(
        query_type='nucl', db_type='nucl', file_type='blast_db_ffn'
    ),
    blastn_fna=dict(
        query_type='nucl', db_type='nucl', file_type='blast_db_fna'
    ),
    blastp=dict(
        query_type='prot', db_type='prot', file_type='blast_db_faa'
    ),
    blastx=dict(
        query_type='nucl', db_type='prot', file_type='blast_db_faa'
    ),
    tblastn_ffn=dict(
        query_type='prot', db_type='nucl', file_type='blast_db_ffn'
    ),
    tblastn_fna=dict(
        query_type='prot', db_type='nucl', file_type='blast_db_fna'
    )
)


def blast_view(request):
    context = extract_errors(request, dict(title='Blast'))

    context['genome_to_species'] = '{}'

    if contains_data(request, 'genomes'):
        qs = extract_data(request, 'genomes', list=True)

        try:
            magic_query_manager = MagicQueryManager(queries=qs)
            context['magic_query_manager'] = magic_query_manager
        except (ValueError, MagicError) as e:
            context['error_danger'].append(str(e))

    return render(request, 'website/blast.html', context)


def blast_submit(request):
    if not request.method == 'POST':
        return HttpResponseBadRequest('Only POST requests allowed.')

    for i in ['blast_input', 'blast_type', 'genomes[]']:
        if not i in request.POST:
            return JsonResponse(dict(success='false', message='Request failed: does not include. ' + i), status=500)

    try:
        magic_query_manager = MagicQueryManager(queries=request.POST['genomes[]'].split(' '))
        genomes = magic_query_manager.all_genomes
    except Exception as e:
        return JsonResponse(dict(success='false', message='Request failed: genomes[] incorrect. ' + str(e)), status=500)

    query = request.POST['blast_input']
    blast_type = request.POST['blast_type']
    query_type = CHOICE_TO_SETTINGS[blast_type]['query_type']
    db_type = CHOICE_TO_SETTINGS[blast_type]['db_type']
    blast_algorithm = request.POST['blast_type'].split('_')[0]

    # load kwargs
    kwargs = request.POST.get('blast_kwargs', '')
    try:
        kwargs = Blast.parse_kwarg_string(kwargs)
        kwargs = Blast.clean_kwargs(kwargs)
        kwargs = {k.removeprefix('-'): a for k, a in kwargs.items()}
    except Exception as e:
        return JsonResponse(dict(success='false', message='Blast failed. Additional BLAST parameters are bad:' + str(e)), status=500)

    file_type = CHOICE_TO_SETTINGS[blast_type]['file_type']

    fasta_files = [getattr(genome.genomecontent, file_type)(relative=True) for genome in genomes]

    # make hashable for caching
    fasta_files = tuple(sorted(set(fasta_files)))

    try:
        blast_output = calculate_blast(fasta_string=query, db=fasta_files, mode=blast_algorithm, **kwargs)
    except Exception as e:
        return JsonResponse(dict(success='false', message='Blast failed. Reason:' + str(e)), status=500)

    return HttpResponse(blast_output, content_type="text/plain")

website/views/ClickMenu.py
from django.shortcuts import render
from website.models import TaxID, Annotation, Genome, Organism, Gene


def click_view(request):
    context = dict(
        title='Test Click Menu',
        taxids=TaxID.objects.all()[:5],
        annotations=Annotation.objects.all().distinct('anno_type'),
        genomes=Genome.objects.order_by('-contaminated', '-representative', 'organism__restricted').all()[:5],
        organisms=Organism.objects.order_by('-restricted').all()[:5],
        genes=Gene.objects.all()[:5]
    )

    return render(request, 'global/test_click_menu.html', context)

website/templates/global/base.html
{% load ogb_tags %}{% load static %}
<!DOCTYPE html>
<html lang="en-US">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <title>{% if title %}{{ title }} - {% endif %}OpenGenomeBrowser</title>
    <link rel="shortcut icon" type="image/svg+xml" href="{% static 'global/customicons/ogb-circle.svg' %}">

    <!-- jquery 3.4.1 -->
    <script src="{% static 'global/js/jquery-3.6.0.min.js' %}"></script>

    <!-- JQuery-UI (without Widgets>Tooltip) -->
    <script type="text/javascript" src="{% static 'global/js/jquery-ui.min.js' %}"></script>
    <link href="{% static 'global/css/jquery-ui.min.css' %}" rel="stylesheet"/>

    <!-- bootstrap 4.3.1 -->
    <script src="{% static 'global/js/popper.min.js' %}"></script>
    <script src="{% static 'global/js/bootstrap.min.js' %}"></script>

    <!-- basic css -->
    <link rel="stylesheet" type="text/css" href="{% static 'global/css/base.css' %}"/>

    <!-- sidebar -->
    <script src="{% static 'global/js/sidebar.js' %}"></script>
    <link rel="stylesheet" type="text/css" href="{% static 'global/css/sidebar.css' %}"/>

    <!-- navbar -->
    <link rel="stylesheet" href="{% static 'global/css/bootstrap.min.css' %}">

    <!-- Base -->
    <script src="{% static 'global/js/base.js' %}"></script>

    <!-- ogb-tags -->
    <link rel="stylesheet" type="text/css" href="{% static 'global/css/ogb-tag.css' %}"/>

    <!-- ClickMenu -->
    <script src="{% static 'global/js/ogb-context-menus.js' %}"></script>
    <link rel="stylesheet" type="text/css" href="{% static 'global/css/ogb-context-menus.css' %}"/>

    <!-- CRF Cookie -->
    <script type="text/javascript" src="{% static 'global/js/getCookie.js' %}"></script>
    {% block styles %}{% endblock %}
</head>

<body id="ogb-body" class="ogb-body">


<!--Sidebar-->
<div id="ogbSidenav" class="sidenav">
    <div id="sidebar-content">
        {% block sidebar %}{% endblock %}
    </div>
</div>


<!--Navbar-->
<nav class="navbar navbar-dark bg-dark fixed-top">
    <!-- logo and text -->
    <a class="navbar-brand" href="/" style="font-family: 'ogbFont'">
        <img src="{% static 'global/customicons/ogb-circle.svg' %}" id="ogb-logo-circle" width="30" height="30"
             class="d-inline-block align-top">
        <span id="ogb-logo-text">OpenGenomeBrowser</span>
    </a>


    <div class="navbar-nav ml-auto navbar-padding" style="position: relative">
        <a class="nav-link text-nowrap {% if request.resolver_match.url_name == 'genomes' %}active{% endif %}"
           href="{% url 'website:genomes' %}{% default_genomes_table_url %}"
        >Genomes</a>
        {% if request.resolver_match.url_name == 'index' %}
            <div id="speech-bubble" class="black-links">
                Click here to start exploring genomes!
            </div>
        {% endif %}

    </div>


    <!-- tools -->
    <div class="nav-item dropdown">
        <button class="btn btn-outline-light my-2 my-sm-0 dropdown-toggle" id="navbarDropdown" data-toggle="dropdown"
                aria-haspopup="true">
            Tools
        </button>
        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <a class="dropdown-item context-menu-icon context-menu-icon-pathway {% if request.resolver_match.url_name == 'pathway' %}active{% endif %}"
               href="{% url 'website:pathway' %}">
                Pathways
            </a>
            <a class="dropdown-item context-menu-icon context-menu-icon-annotations {% if request.resolver_match.url_name == 'annotation-search' %}active{% endif %}"
               href="{% url 'website:annotation-search' %}">
                Annotation search
            </a>
            <a class="dropdown-item context-menu-icon context-menu-icon-flower-plot {% if request.resolver_match.url_name == 'flower-plot' %}active{% endif %}"
               href="{% url 'website:flower-plot' %}">
                Flower plot
            </a>
            <a class="dropdown-item context-menu-icon context-menu-icon-gene-comparison {% if request.resolver_match.url_name == 'compare-genes' %}active{% endif %}"
               href="{% url 'website:compare-genes' %}">
                Compare genes
            </a>
            <a class="dropdown-item context-menu-icon context-menu-icon-gene-trait-matching {% if request.resolver_match.url_name == 'gene-trait-matching' %}active{% endif %}"
               href="{% url 'website:gene-trait-matching' %}">
                Gene trait matching
            </a>
            <a class="dropdown-item context-menu-icon context-menu-icon-blast {% if request.resolver_match.url_name == 'blast' %}active{% endif %}"
               href="{% url 'website:blast' %}">
                Blast
            </a>
            <a class="dropdown-item context-menu-icon context-menu-icon-tree {% if request.resolver_match.url_name == 'trees' %}active{% endif %}"
               href="{% url 'website:trees' %}">
                Trees
            </a>
            <a class="dropdown-item context-menu-icon context-menu-icon-dotplot {% if request.resolver_match.url_name == 'dotplot' %}active{% endif %}"
               href="{% url 'website:dotplot' %}">
                Dotplot
            </a>
            <a class="dropdown-item context-menu-icon context-menu-icon-downloader {% if request.resolver_match.url_name == 'downloader' %}active{% endif %}"
               href="{% url 'website:downloader' %}">
                Downloader
            </a>
            <div class="dropdown-divider"></div>
            <a class="dropdown-item context-menu-icon context-menu-icon-help {% if no_help %}disabled{% endif %}"
               href="https://opengenomebrowser.github.io/tutorials/{{ request.resolver_match.url_name }}.html">
                Get help with this page
            </a>
        </div>
    </div>


    <!-- account -->
    <div class="btn-group navbar-padding">
        <div data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <img src="{% static 'global/ionicons/md-person.svg' %}" id="account" alt="account"
                 class="d-inline-block svg-invert navbar-image">
        </div>
        <div class="dropdown-menu dropdown-menu-right">
            {% if user.is_authenticated %}
                <h6 class="dropdown-header">Welcome, {{ user.get_username }}!</h6>
                <div class="dropdown-item">
                    <a class="btn btn-warning btn-account" href="{% url 'logout' %}">
                        Log out
                    </a>
                </div>

                {% if user.is_staff %}
                    <div class="dropdown-divider"></div>

                    <div class="dropdown-item">
                        <a class="btn btn-success btn-account" href="{% url 'admin:index' %}">
                            Administration
                        </a>
                    </div>

                    {% if admin_actions %}
                        <div class="dropdown-divider"></div>

                        {% for admin_action in admin_actions %}
                            <div class="dropdown-item">
                                <a class="btn btn-secondary btn-account" href="{{ admin_action.url }}">
                                    {{ admin_action.action }}
                                </a>
                            </div>
                        {% endfor %}
                    {% endif %}


                {% endif %}

                <div class="dropdown-divider"></div>

                <div class="dropdown-item">
                    <a class="btn btn-info btn-account" href="{% url 'password_change' %}">
                        Change password
                    </a>
                </div>
                <div class="dropdown-item">
                    <a class="btn btn-info btn-account" href="{% url 'password_reset' %}">
                        Reset password
                    </a>
                </div>
            {% else %}
                <h6 class="dropdown-header">Welcome to OpenGenomeBrowser!</h6>
                <div class="dropdown-item">
                    <a class="btn btn-primary btn-account" href="{% url 'login' %}">
                        Log in
                    </a>
                </div>
            {% endif %}
        </div>
    </div>

    <!-- toggle sidebar -->
    <div class="nav-item">
        <img src="{% static 'global/ionicons/md-settings.svg' %}" id="settings-wheel" alt="settings wheel"
             class="d-inline-block svg-invert navbar-padding navbar-image" onclick="toggleNav(event)">
    </div>

</nav>

{% block breadcrum %}{% endblock %}

<section>
    <!-- warning or danger messages -->
    {% for error in error_warning %}
        <!-- warning -->
        <div class="container black-links">
            <div class="alert alert-warning" role="alert">
                {{ error }}
            </div>
        </div>
    {% endfor %}
    {% for error in error_danger %}
        <!-- danger -->
        <div class="container black-links">
            <div class="alert alert-danger" role="alert">
                {{ error }}
            </div>
        </div>
    {% endfor %}
    {% for error in error_info %}
        <!-- info -->
        <div class="container black-links mt-3">
            <div class="alert alert-info" role="alert">
                {{ error }}
            </div>
        </div>
    {% endfor %}

</section>

{% block body %}{% endblock %}

<section>
    {% for error in error_info_bottom %}
        <!-- info -->
        <div class="container black-links mt-3">
            <div class="alert alert-info" role="alert">
                {{ error|safe }}
            </div>
        </div>
    {% endfor %}
</section>

</body>

<script>
    const placeholders = {{ placeholders|safe }}
</script>

{% block end %}{% endblock %}


</html>

website/templates/global/pagination_snippet.html
{% load ogb_tags %}
{% if page_obj %}
    <ul class="pagination" style="width: min-content; margin-top: .75rem; margin-bottom: 0;">

        {% if page_obj.has_previous %}
            <li class="page-item">
                <a class="page-link" href="?{% param_replace page=1 %}" aria-label="First">
                    <span aria-hidden="true">1</span>
                </a>
            </li>
        {% endif %}


        {% if page_obj.number > 3 %}
            <li class="page-item disabled">
                <p class="page-link" aria-label="Current">
                    <span aria-disabled="true">...</span>
                </p>
            </li>
        {% endif %}


        {% if page_obj.number > 2 %}
            <li class="page-item">
                <a class="page-link" href="?{% param_replace page=page_obj.previous_page_number %}" aria-label="Previous">
                    <span aria-hidden="true">{{ page_obj.previous_page_number }}</span>
                </a>
            </li>
        {% endif %}


        <li class="page-item active">
            <p class="page-link" aria-label="Current">
                <span aria-hidden="true">{{ page_obj.number }}</span>
            </p>
        </li>


        {% cur_plus_n_st_last n=1 cur=page_obj.number last=paginator.num_pages as temp_ %}
        {% if temp_ %}
            <li class="page-item">
                <a class="page-link" href="?{% param_replace page=page_obj.next_page_number %}" aria-label="Next">
                    <span aria-hidden="true">{{ page_obj.next_page_number }}</span>
                </a>
            </li>
        {% endif %}


        {% cur_plus_n_st_last n=2 cur=page_obj.number last=paginator.num_pages as temp_ %}
        {% if temp_ %}
            <li class="page-item disabled">
                <p class="page-link" aria-label="Current">
                    <span aria-disabled="true">...</span>
                </p>
            </li>
        {% endif %}


        {% if page_obj.has_next %}
            <li class="page-item">
                <a class="page-link" href="?{% param_replace page=paginator.num_pages %}" aria-label="Last">
                    <span aria-hidden="true">{{ paginator.num_pages }}</span>
                </a>
            </li>
        {% endif %}

    </ul>

{% endif %}